/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoda31217;

import org.apache.commons.math3.primes.Primes;

public class Library {

  public boolean isPrime(int number) {
    return Primes.isPrime(number);
  }
}
