/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.yoda31217.samodelkin.math.error;

import static com.google.common.base.Preconditions.checkArgument;
import static java.lang.Double.POSITIVE_INFINITY;
import static java.lang.Math.abs;
import static java.util.Locale.ENGLISH;

import java.util.function.Function;

public class DoubleWithError {

  private final double value;

  private final double error;

  private DoubleWithError(double value, double error) {
    this.value = value;
    checkArgument(error >= 0, "Error should be >=0, but was: %s.", error);
    this.error = error;
  }

  public static DoubleWithError newDoubleWithError(double value, double error) {
    return new DoubleWithError(value, error);
  }

  public static DoubleWithError newDoubleWithRelativeError(double value, double relativeError) {
    return new DoubleWithError(value, abs(value) * relativeError);
  }

  public double getValue() {
    return value;
  }

  public double getError() {
    return error;
  }

  public double getRelativeError() {
    return value == 0 ? POSITIVE_INFINITY : error / abs(value);
  }

  public String format(Function<Double, String> valueFormatter) {
    return String.format(ENGLISH, "%s±%s(%.2f%%)",
      valueFormatter.apply(value),
      valueFormatter.apply(error),
      100 * getRelativeError());
  }

  public DoubleWithError add(DoubleWithError other) {
    return newDoubleWithError(value + other.value, error + other.error);
  }

  public DoubleWithError sub(DoubleWithError other) {
    return newDoubleWithError(value - other.value, error + other.error);
  }

  public DoubleWithError mul(DoubleWithError other) {
    return newDoubleWithRelativeError(value * other.value, getRelativeError() + other.getRelativeError());
  }

  public DoubleWithError div(DoubleWithError other) {
    return newDoubleWithRelativeError(value / other.value, getRelativeError() + other.getRelativeError());
  }
}
