/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoda31217;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class LibraryTest {

  @Test
  void someLibraryMethodReturnsTrue() {
    Library classUnderTest = new Library();
    assertThat(classUnderTest.isPrime(3)).isTrue();
  }
}
