/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.yoda31217;

public class DoubleWithError {

  private final double value;

  private final double error;

  private DoubleWithError(double value, double error) {
    this.value = value;
    this.error = error;
  }

  public static DoubleWithError newDoubleWithError(double value, double error) {
    return new DoubleWithError(value, error);
  }

  public double getValue() {
    return value;
  }

  public double getError() {
    return error;
  }
}
