/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.yoda31217;

import static com.google.common.base.Preconditions.checkArgument;
import static java.lang.Math.abs;

public class DoubleWithError {

  private final double value;

  private final double error;

  private DoubleWithError(double value, double error) {
    this.value = value;
    checkArgument(error >= 0, "Error should be >=0, but was: %s.", error);
    this.error = error;
  }

  public static DoubleWithError newDoubleWithError(double value, double error) {
    return new DoubleWithError(value, error);
  }

  public static DoubleWithError newDoubleWithRelativeError(double value, double relativeError) {
    return new DoubleWithError(value, abs(value) * relativeError);
  }

  public double getValue() {
    return value;
  }

  public double getError() {
    return error;
  }

  public double getRelativeError() {
    return error / abs(value);
  }
}
